name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  sheriff:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR title
        uses: teneplaysofficial/sheriff@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn fmt:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn docs

  diff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: |
          yarn predocs
          yarn prebuild
          yarn fmt src/index.ts examples/README.md
      - run: |
          CHANGED_FILES=$(git diff --name-only src/index.ts examples/README.md)
          if [ -n "$CHANGED_FILES" ]; then
            echo "The following files are not up to date."
            echo ""
            echo "Please update and commit the following file(s):"
            echo "$CHANGED_FILES" | sed 's/^/  - /'
            echo ""
            echo "Run locally to fix:"
            echo "  yarn predocs && yarn prebuild && yarn fmt src/index.ts examples/README.md"
            echo ""
            echo "Showing diffs for changed files:"
            echo "----------------------------------------"
            git diff src/index.ts examples/README.md | sed 's/^/    /'
            echo "----------------------------------------"
            exit 1
          else
            echo "No changes detected, All generated files are up to date."
          fi

  jsr-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish --dry-run
